import React from 'react';
import { StressTestMode } from '../types';
import { Bug, X, AlertTriangle, ShieldCheck, Zap } from 'lucide-react';

interface StressTestModalProps {
  isOpen: boolean;
  onClose: () => void;
  activeTestMode: StressTestMode;
  onSelectTestMode: (mode: StressTestMode) => void;
}

const TEST_MODES: { mode: StressTestMode; title: string; desc: string; icon: string }[] = [
  {
    mode: 'none',
    title: 'Normal Production Mode',
    desc: 'Valid structured JSON generated by Gemini API with schema validation.',
    icon: '✅',
  },
  {
    mode: 'malformed_json',
    title: 'Malformed / Unclosed JSON',
    desc: 'Simulates AI output returning truncated or broken syntax JSON string.',
    icon: '⚠️',
  },
  {
    mode: 'wrong_schema',
    title: 'Unexpected / Missing Schema Fields',
    desc: 'Simulates AI output missing key fields or returning wrong data types.',
    icon: '🔄',
  },
  {
    mode: 'empty_response',
    title: 'Empty Response String',
    desc: 'Simulates AI returning an empty or blank string payload.',
    icon: '🚫',
  },
  {
    mode: 'server_error',
    title: 'HTTP 500 / API Network Crash',
    desc: 'Simulates backend server failure or rate limiting (429/500).',
    icon: '💥',
  },
  {
    mode: 'slow_timeout',
    title: 'High Network Latency / Delay (6s)',
    desc: 'Simulates slow LLM inference to test loading state spinners.',
    icon: '⏳',
  },
];

export const StressTestModal: React.FC<StressTestModalProps> = ({
  isOpen,
  onClose,
  activeTestMode,
  onSelectTestMode,
}) => {
  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-[#0A0A0A] rounded-2xl border border-white/10 max-w-lg w-full p-6 shadow-2xl space-y-5 animate-in fade-in zoom-in duration-200 text-white relative">
        <div className="absolute top-0 left-0 right-0 h-1 bg-[#FF3B30]" />

        <div className="flex items-center justify-between pb-3 border-b border-white/10">
          <div className="flex items-center gap-2 text-[#FF3B30] font-mono font-bold text-xs uppercase tracking-widest">
            <Bug className="h-5 w-5" />
            Interview Stress Test & Resilience Panel
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg hover:bg-white/10 text-white/60"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="p-3 bg-[#FF3B30]/10 border border-[#FF3B30]/30 rounded-xl text-xs text-white/90 space-y-1">
          <span className="font-mono font-bold uppercase tracking-wider text-[#FF3B30] flex items-center gap-1.5">
            <ShieldCheck className="h-4 w-4" />
            LIVE INTERVIEW RESILIENCE DEMO:
          </span>
          <p className="font-light text-white/70 leading-relaxed">
            Inject bad AI responses, unclosed JSON blocks, or network timeouts live to demonstrate auto-repair heuristics and zero-crash execution.
          </p>
        </div>

        <div className="space-y-2.5 max-h-80 overflow-y-auto pr-1">
          {TEST_MODES.map((item) => {
            const isSelected = activeTestMode === item.mode;

            return (
              <div
                key={item.mode}
                onClick={() => {
                  onSelectTestMode(item.mode);
                  onClose();
                }}
                className={`p-3.5 rounded-xl border cursor-pointer transition-all flex items-start gap-3 ${
                  isSelected
                    ? 'bg-[#FF3B30]/20 border-[#FF3B30] text-white font-semibold'
                    : 'bg-black/60 border-white/10 hover:border-white/30 text-white/80'
                }`}
              >
                <span className="text-lg">{item.icon}</span>
                <div className="space-y-0.5 text-xs">
                  <div className="font-bold flex items-center justify-between">
                    <span className="font-mono uppercase tracking-wider">{item.title}</span>
                    {isSelected && (
                      <span className="text-[10px] font-mono uppercase font-bold text-[#FF3B30] px-2 py-0.5 rounded bg-[#FF3B30]/20 border border-[#FF3B30]/40">
                        ACTIVE
                      </span>
                    )}
                  </div>
                  <p className="text-white/50 font-light leading-relaxed">
                    {item.desc}
                  </p>
                </div>
              </div>
            );
          })}
        </div>

        <div className="pt-2 flex justify-end">
          <button
            onClick={onClose}
            className="px-5 py-2.5 rounded-xl bg-[#FF3B30] text-white font-mono uppercase tracking-widest font-bold text-xs hover:bg-[#e03126] transition-colors shadow-lg shadow-[#FF3B30]/20"
          >
            CONFIRM SELECTION
          </button>
        </div>
      </div>
    </div>
  );
};
